app = 'react-gsap-scroll-trigger'
primary_region = 'lhr'

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

kill_signal = "SIGINT"
kill_timeout = 5